using System.Collections.Generic;
using UnityEngine;

namespace PrimalFrontier.UI
{
    /// <summary>
    /// Look of the whole UI: dark translucent panels with worn leather / wood / stone accents and aged paper for the
    /// journal. Textures live in Resources/UI (generated by Tools/UI/ui_textures.py), fonts in Resources/Fonts (OFL).
    /// Everything has a code fallback so a missing texture never breaks a screen.
    /// </summary>
    public static class UIStyle
    {
        public static readonly Color Text = new Color(0.93f, 0.89f, 0.80f);
        public static readonly Color TextDim = new Color(0.70f, 0.66f, 0.58f);
        public static readonly Color TextDark = new Color(0.20f, 0.14f, 0.09f);     // on paper
        public static readonly Color Accent = new Color(0.86f, 0.64f, 0.32f);       // amber
        public static readonly Color Bad = new Color(0.86f, 0.33f, 0.26f);
        public static readonly Color Good = new Color(0.55f, 0.78f, 0.42f);
        public static readonly Color Panel = new Color(0.07f, 0.06f, 0.05f, 0.78f);
        public static readonly Color Health = new Color(0.76f, 0.18f, 0.14f);
        public static readonly Color Hunger = new Color(0.85f, 0.56f, 0.20f);
        public static readonly Color Thirst = new Color(0.25f, 0.55f, 0.82f);
        public static readonly Color Stamina = new Color(0.78f, 0.74f, 0.32f);
        public static readonly Color Warm = new Color(0.90f, 0.52f, 0.25f);
        public static readonly Color Cold = new Color(0.45f, 0.70f, 0.95f);

        static readonly Dictionary<string, Sprite> _sprites = new Dictionary<string, Sprite>();
        static Font _body, _head, _hand;

        public static Font Body => _body ??= LoadFont("Fonts/AlegreyaSans-Regular");
        public static Font Head => _head ??= LoadFont("Fonts/AlegreyaSC-Bold");
        public static Font Hand => _hand ??= LoadFont("Fonts/Alegreya-Italic");

        static Font LoadFont(string path)
        {
            var f = Resources.Load<Font>(path);
            if (f == null) f = Resources.GetBuiltinResource<Font>("LegacyRuntime.ttf");
            return f;
        }

        /// <summary>9-sliced sprite from Resources/UI/name.png (border in px); white fallback</summary>
        public static Sprite Sprite(string name, int border = 0)
        {
            string key = name + ":" + border;
            if (_sprites.TryGetValue(key, out var s) && s) return s;
            var tex = Resources.Load<Texture2D>("UI/" + name);
            if (tex == null)
            {
                tex = new Texture2D(4, 4); var px = new Color[16]; for (int i = 0; i < 16; i++) px[i] = Color.white; tex.SetPixels(px); tex.Apply();
                border = 1;
            }
            int b = Mathf.Min(border, tex.width / 2 - 1, tex.height / 2 - 1);
            s = UnityEngine.Sprite.Create(tex, new Rect(0, 0, tex.width, tex.height), new Vector2(0.5f, 0.5f), 100f, 0, SpriteMeshType.FullRect, new Vector4(b, b, b, b));
            s.name = name;
            _sprites[key] = s;
            return s;
        }

        public static Sprite PanelDark => Sprite("ui_panel", 28);
        public static Sprite Leather => Sprite("ui_leather", 40);
        public static Sprite Wood => Sprite("ui_wood", 20);
        public static Sprite Stone => Sprite("ui_stone", 20);
        public static Sprite Paper => Sprite("ui_paper", 40);
        public static Sprite Slot => Sprite("ui_slot", 14);
        public static Sprite SlotActive => Sprite("ui_slot_active", 14);
        public static Sprite Button => Sprite("ui_button", 16);
        public static Sprite BarBack => Sprite("ui_bar_back", 6);
        public static Sprite BarFill => Sprite("ui_bar_fill", 3);
        public static Sprite Vignette => Sprite("ui_vignette", 0);
        public static Sprite Icon(string n) => Sprite("icon_" + n, 0);
    }
}
